const sampleData = [

    {
        "name": "Central City Parking",
        "address": "MG Road",
        "city": "Pune",
        "description": "Secure parking near shopping area",
        "pricePerHour": 30,
        "totalSlots": 100,
        "availableSlots": 45,
        "coordinates": { "lat": 18.5204, "lng": 73.8567 },
        "amenities": ["CCTV", "Security", "EV Charging"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Mall Parking Zone",
        "address": "Phoenix Mall",
        "city": "Pune",
        "description": "Covered parking for mall visitors",
        "pricePerHour": 50,
        "totalSlots": 200,
        "availableSlots": 120,
        "coordinates": { "lat": 18.5679, "lng": 73.9143 },
        "amenities": ["CCTV", "Covered"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Railway Station Parking",
        "address": "Pune Junction",
        "city": "Pune",
        "description": "24/7 parking near station",
        "pricePerHour": 20,
        "totalSlots": 150,
        "availableSlots": 60,
        "coordinates": { "lat": 18.5286, "lng": 73.8746 },
        "amenities": ["Security"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Airport Parking",
        "address": "Lohegaon Airport",
        "city": "Pune",
        "description": "Long term parking",
        "pricePerHour": 60,
        "totalSlots": 300,
        "availableSlots": 200,
        "coordinates": { "lat": 18.5822, "lng": 73.9197 },
        "amenities": ["CCTV", "Security", "EV Charging"],
        "image": "",
        "isActive": true
    },
    {
        "name": "IT Park Parking",
        "address": "Hinjewadi Phase 1",
        "city": "Pune",
        "description": "Parking for IT employees",
        "pricePerHour": 25,
        "totalSlots": 250,
        "availableSlots": 80,
        "coordinates": { "lat": 18.5913, "lng": 73.7389 },
        "amenities": ["CCTV", "Covered"],
        "image": "",
        "isActive": true
    },

    {
        "name": "City Center Parking",
        "address": "FC Road",
        "city": "Pune",
        "description": "Convenient parking in city center",
        "pricePerHour": 35,
        "totalSlots": 120,
        "availableSlots": 30,
        "coordinates": { "lat": 18.5236, "lng": 73.8478 },
        "amenities": ["Security"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Hospital Parking",
        "address": "Ruby Hall Clinic",
        "city": "Pune",
        "description": "Parking for hospital visitors",
        "pricePerHour": 15,
        "totalSlots": 80,
        "availableSlots": 20,
        "coordinates": { "lat": 18.5362, "lng": 73.8767 },
        "amenities": ["Security"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Cinema Parking",
        "address": "PVR Cinemas",
        "city": "Pune",
        "description": "Parking for movie goers",
        "pricePerHour": 40,
        "totalSlots": 90,
        "availableSlots": 50,
        "coordinates": { "lat": 18.5600, "lng": 73.8070 },
        "amenities": ["CCTV"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Bus Stand Parking",
        "address": "Swargate",
        "city": "Pune",
        "description": "Parking near bus depot",
        "pricePerHour": 10,
        "totalSlots": 140,
        "availableSlots": 70,
        "coordinates": { "lat": 18.5010, "lng": 73.8630 },
        "amenities": ["Security"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Market Yard Parking",
        "address": "Gultekdi",
        "city": "Pune",
        "description": "Parking for traders",
        "pricePerHour": 20,
        "totalSlots": 160,
        "availableSlots": 90,
        "coordinates": { "lat": 18.4967, "lng": 73.8800 },
        "amenities": ["CCTV"],
        "image": "",
        "isActive": true
    },

    {
        "name": "College Parking",
        "address": "COEP",
        "city": "Pune",
        "description": "Student parking",
        "pricePerHour": 5,
        "totalSlots": 70,
        "availableSlots": 25,
        "coordinates": { "lat": 18.5291, "lng": 73.8565 },
        "amenities": [],
        "image": "",
        "isActive": true
    },
    {
        "name": "Temple Parking",
        "address": "Dagdusheth Temple",
        "city": "Pune",
        "description": "Parking for devotees",
        "pricePerHour": 10,
        "totalSlots": 60,
        "availableSlots": 10,
        "coordinates": { "lat": 18.5164, "lng": 73.8560 },
        "amenities": ["Security"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Park View Parking",
        "address": "Saras Baug",
        "city": "Pune",
        "description": "Scenic parking area",
        "pricePerHour": 15,
        "totalSlots": 75,
        "availableSlots": 40,
        "coordinates": { "lat": 18.5030, "lng": 73.8520 },
        "amenities": ["CCTV"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Residential Parking",
        "address": "Kothrud",
        "city": "Pune",
        "description": "Parking for residents",
        "pricePerHour": 12,
        "totalSlots": 110,
        "availableSlots": 60,
        "coordinates": { "lat": 18.5074, "lng": 73.8077 },
        "amenities": ["Security"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Metro Station Parking",
        "address": "Vanaz Metro",
        "city": "Pune",
        "description": "Parking near metro",
        "pricePerHour": 18,
        "totalSlots": 130,
        "availableSlots": 55,
        "coordinates": { "lat": 18.5070, "lng": 73.7840 },
        "amenities": ["CCTV"],
        "image": "",
        "isActive": true
    },

    {
        "name": "EV Hub Parking",
        "address": "Baner",
        "city": "Pune",
        "description": "EV friendly parking",
        "pricePerHour": 45,
        "totalSlots": 90,
        "availableSlots": 35,
        "coordinates": { "lat": 18.5590, "lng": 73.7860 },
        "amenities": ["EV Charging"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Luxury Parking",
        "address": "Koregaon Park",
        "city": "Pune",
        "description": "Premium parking",
        "pricePerHour": 80,
        "totalSlots": 60,
        "availableSlots": 20,
        "coordinates": { "lat": 18.5360, "lng": 73.8950 },
        "amenities": ["CCTV", "Security", "Covered"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Industrial Parking",
        "address": "Bhosari",
        "city": "Pune",
        "description": "Parking for industrial workers",
        "pricePerHour": 10,
        "totalSlots": 200,
        "availableSlots": 150,
        "coordinates": { "lat": 18.6200, "lng": 73.8400 },
        "amenities": [],
        "image": "",
        "isActive": true
    },
    {
        "name": "Weekend Parking",
        "address": "Lavasa Road",
        "city": "Pune",
        "description": "Tourist parking",
        "pricePerHour": 25,
        "totalSlots": 100,
        "availableSlots": 70,
        "coordinates": { "lat": 18.4090, "lng": 73.5060 },
        "amenities": ["CCTV"],
        "image": "",
        "isActive": true
    },
    {
        "name": "Expressway Parking",
        "address": "Mumbai-Pune Expressway",
        "city": "Pune",
        "description": "Highway parking",
        "pricePerHour": 30,
        "totalSlots": 180,
        "availableSlots": 95,
        "coordinates": { "lat": 18.7400, "lng": 73.4000 },
        "amenities": ["Security"],
        "image": "",
        "isActive": true
    }

];


module.exports = { data: sampleData };